### ISSUE TITLE
Does the secret integer key in the constructor have to be a special format value/ char limit ?

### ISSUE THREAD

**Issue by scribbb** [marekweb/opaque-id#2]
For example if I use the key 68zr1468r4a6, it returns 96e2554b

But then if I add some letters to the key : 68zr1468r4a6xre68g2 it still returns 96e2554b.

Thanks a lot !

**Comment by javierlabanca** [comment]
I always get the same outputs no matter what key I use. For instance:

1 -> 120000
2 -> 7432ed58
3 -> 435304f1 

Any clues as to what the cause might be?
Thanks!

**Comment by javierlabanca** [comment]
Hi,

I'm having the same problem: No matter what key I use, the output is always the same. For instance:

1 -> df310013
2 -> 61be04f1
3 -> b300ed58

Any clues?
Thanks!
